version: '3.7'

services:

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: Shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'